### ISSUE TITLE
'RDRNet is not in the model registry

### ISSUE THREAD

**Issue by eyusafg** [gyyang23/RDRNet#3]
KeyError: "class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: 'RDRNet is not in the model registry. Please check whether the value of `RDRNet` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"

**Comment by zhoukaiyu123** [comment]
请问你的解决了吗？

**Comment by zhoukaiyu123** [comment]
我也遇到了相同的问题
Traceback (most recent call last):
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 87, in __init__
    self.backbone = MODELS.build(backbone)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'RDRNet is not in the model registry. Please check whether the value of `RDRNet` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mmsegmentation/tools/train.py", line 106, in <module>
    main()
  File "./mmsegmentation/tools/train.py", line 95, in main
    runner = Runner.from_cfg(cfg)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
KeyError: "class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: 'RDRNet is not in the model registry. Please check whether the value of `RDRNet` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"

**Comment by klxg001** [comment]
请问你解决了吗

**Comment by PINTO0309** [comment]
```bash
cd mmsegmentation
python setup.py install
pip install -v -e .
cd ..
```
