### ISSUE TITLE
注册表中找不到模型

### ISSUE THREAD

**Issue by zhoukaiyu123** [gyyang23/RDRNet#4]
Traceback (most recent call last):
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 122, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 87, in __init__
    self.backbone = MODELS.build(backbone)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 100, in build_from_cfg
    raise KeyError(
KeyError: 'RDRNet is not in the model registry. Please check whether the value of `RDRNet` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mmsegmentation/tools/train.py", line 128, in <module>
    main()
  File "mmsegmentation/tools/train.py", line 117, in main
    runner = Runner.from_cfg(cfg)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 439, in from_cfg
    runner = cls(
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 406, in __init__
    self.model = self.build_model(model)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/runner/runner.py", line 813, in build_model
    model = MODELS.build(model)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/registry.py", line 548, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 250, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhoukaiyu/anaconda3/envs/rdrnet/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 144, in build_from_cfg
    raise type(e)(
KeyError: "class `EncoderDecoder` in mmseg/models/segmentors/encoder_decoder.py: 'RDRNet is not in the model registry. Please check whether the value of `RDRNet` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'"

**Comment by gyyang23** [comment]
安装mmsegmentation了吗？进入mmsegmentation目录然后运行pip install -v -e .

**Comment by zhoukaiyu123** [comment]
很抱歉打扰您，请问您正常都是怎么训练的，我用的配置文件s-simple原始下载的没有改动，数据集是cityscapes，但是精度总是在74左右bs=6用的a100显卡，iters=120000就是一直在74左右，有没有什么好的办法，谢谢您，期待您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gyyang23/RDRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月22日(星期一) 凌晨0:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gyyang23/RDRNet] 注册表中找不到模型 (Issue #4)





 
安装mmsegmentation了吗？进入mmsegmentation目录然后运行pip install -v -e .

**Comment by zhoukaiyu123** [comment]
很抱歉打扰您，请问您正常都是怎么训练的，我用的配置文件s-simple原始下载的没有改动，数据集是cityscapes，但是精度总是在74左右bs=6用的a100显卡，iters=120000就是一直在74左右，有没有什么好的办法，附上我的训练log，谢谢您，期待您的回复




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "gyyang23/RDRNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月22日(星期一) 凌晨0:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gyyang23/RDRNet] 注册表中找不到模型 (Issue #4)





 
安装mmsegmentation了吗？进入mmsegmentation目录然后运行pip install -v -e .
